### ISSUE TITLE
Legitamate IOD formats are not being accepted

### ISSUE THREAD

**Issue by johngribbin** [consensys-space/trusat-orbit#14]
1. When a user submits an IOD that doesn't contain `Angle Code` or `Epoch Code`:
- The default value for Angle format code is set to `-1`
- The default value for Epoch code is set to `-1`

This can be tested by submitting a `Clouded out` submission, which sends empty values for both `Angle Code` and `Epoch Code`. This causes problems because both of these values are expected to be one character in length in the database table. 

2. The IOD RegEx is expecting values for both `right ascension` and `declination` if a value of `+` or `-` for `declination/elevation sign` is present (`+` it is automatically entered for the user on the front-end)

**Comment by interplanetarychris** [comment]
Confirmed.  Database schema was set to CHAR(1) values for AngleFormatCode and EpochCode, resulting in "-1" values getting truncated to "-" and triggering the "Data too long for column X" error from MYSQL.

Recommended fix is to update the database schema for those two fields to by TINYINT(4) so that -1 values can be stored.  This allows a history of knowing that the parsed record contained either an (A) invalid EpochCode, or (B) an invalid AngleFormatCode -> both of which result in a -1 for ValidPosition - which allows the system to skip over these when considering position measurements.

Code to modify the live database schema is below - and this should be submitted as a change to https://github.com/consensys-space/trusat-backend/blob/master/database.py to fully close this PR.

`USE appropriate_database';`
`SELECT COUNT(*) FROM ParsedIOD WHERE epoch_code='-';`
`/* Note/review return value for LIMIT below */`
`SELECT COUNT(*) FROM ParsedIOD WHERE angle_format_code='-';`
`/* Note/review return value for LIMIT below */`
`/* Change "invalid/truncated" "-" values to a currently-valid placeholder value */`
`UPDATE ParsedIOD SET epoch_code=9 WHERE epoch_code='-' LIMIT 431;`
`UPDATE ParsedIOD SET angle_format_code=9 WHERE angle_format_code='-' LIMIT 543;`
`/* Alter table structure from CHAR(1) to TINYINT(4) */`
`ALTER TABLE ParsedIOD CHANGE epoch_code epoch_code TINYINT NULL DEFAULT NULL COMMENT '';`
`ALTER TABLE ParsedIOD CHANGE angle_format_code angle_format_code TINYINT NULL DEFAULT NULL COMMENT '';`
`/* Set the previously truncated "-" values to "-1" per original intent */`
`UPDATE ParsedIOD SET epoch_code=-1 WHERE epoch_code=9 LIMIT 431;`
`UPDATE ParsedIOD SET angle_format_code=-1 WHERE angle_format_code=9 LIMIT 543;`

This change has been implemented on the DEV database and tested to work.

**Comment by interplanetarychris** [comment]
> The IOD RegEx is expecting values for both right ascension and declination if a value of + or - for declination/elevation sign is present (+ it is automatically entered for the user on the front-end)

This point appears to be separate - and unrelated to the underlying problem.  The front-end should ideally not encode a sign character in the string, if no values are present which would require a sign.
